apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: django-app
spec:
  selector:
    matchLabels:
      app: django-app
  replicas: 1
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {duration: 30}
      - setWeight: 50
      - pause: {duration: 30}
      - setWeight: 75
      - pause: {duration: 30}
      - setWeight: 100
      - pause: {duration: 30}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: hohyun10/winwinmarket_project:v2
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 130m
          requests:
            cpu: 80m